version: 2.1

commands:
  install-deps:
    steps:
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  login-dockerhub:
    steps:
      - run:
          name: Log in to Docker Hub
          command: docker login -u hbjy -p "$DOCKERHUB_TOKEN"

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.3
    resource_class: small
    steps:
      - checkout
      - install-deps
      - run:
          name: Build CLI
          command: |
            mkdir -p out
            go build -o out/api .
      - store_artifacts:
          path: out/api
          destination: api-linux-amd64
          name: API Binary

  build-docker:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.3
    resource_class: small
    steps:
      - setup_remote_docker:
          docker_layer_caching: true  # default - false
      - login-dockerhub
      - checkout
      - run:
          name: Build hbjy/openschool-api container image
          command: |
            docker build . \
              -t hbjy/openschool-api:${CIRCLE_BRANCH} \
              -t hbjy/openschool-api:${CIRCLE_SHA1}
      - run:
          name: Push hbjy/openschool-api container image
          command: |
            docker push hbjy/openschool-api:${CIRCLE_BRANCH}
            docker push hbjy/openschool-api:${CIRCLE_SHA1}

  lint:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.3
    resource_class: small
    steps:
      - checkout
      - install-deps
      - run:
          name: Install golangci-lint
          command: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint
      - run:
          name: Run golangci-lint
          command: |
            mkdir -p /tmp/test-reports \
            && golangci-lint run \
              --out-format=junit-xml > \
              /tmp/test-reports/junit.xml
      - store_test_results:
          path: /tmp/test-reports

workflows:
  docker-build:
    jobs:
      - build-docker

  lint-build:
    jobs:
      - lint
      - build
