version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.19.3
    steps:
      - checkout
      - run:
          name: Build CLI
          command: |
            mkdir -p out
            go build -o out/api .
      - store_artifacts:
          path: out/api
          destination: api-linux-amd64
          name: API Binary

  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.19.3
    steps:
      - run:
          name: Install golangci-lint
          command: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1

      - checkout
      - run:
          name: Run golangci-lint
          command: |
            mkdir -p /tmp/test-reports \
            && golangci-lint run \
              --out-format=junit-xml > \
              /tmp/test-reports/junit.xml

      - store_test_results:
          path: /tmp/test-reports

workflows:
  lint-build:
    jobs:
      - lint
      - build
